spring:
  cloud:
    stream:
      bindings:
        noiseSensorConsumer-in-0:
          destination: noise-sensor
          consumer:
            useNativeDecoding: true
      kafka:
        bindings:
          noiseSensorConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
                schema.registry.url: http://localhost:8081
                specific.avro.reader: true
